### ISSUE TITLE
"Compress notes" feature

### ISSUE THREAD

**Issue by Frn1** [sevenc-nanashi/MikuMikuWorld4CC#29]
This would be a feature that is very similar to the "shrink" feature, but it would also add Hi-Speed changes to the chart to the layer to make it look like what was originally in the chart.
Here is an example
After using the feature the selected notes would turn from this:
![image](https://github.com/sevenc-nanashi/MikuMikuWorld4CC/assets/20214662/cc12cce0-f291-4d92-9140-d8ac2c914f82)
into this:
![image](https://github.com/sevenc-nanashi/MikuMikuWorld4CC/assets/20214662/7d0874bd-6b00-4f8e-8890-444c133a22b2)

**Comment by mikreo** [comment]
Would it use the current division to compress it, or would it always go by a fixed amount?

**Comment by frn1** [comment]
I was thinking it would compress it as much as possible (like shrink). The idea I had was to make it look like that whole section was for the notes to look the same when played, but suddenly they get "skipped" or "warped" over.

I think should have explained that the slider heads and tails in the second image are 1 tick apart from each other

**Comment by sevenc-nanashi** [comment]
So you mean "Please make shrink keep whether notes have the same ticks or not"?

**Comment by frn1** [comment]
Yeah, basically that but with the option of adding Hi-Speeds to make the notes in game look like they did before.
For example if I use that feature on 2 notes that are ticks beats apart, a 480x * (whatever the Hi-Speed is currently at that tick) gets added to the chart
