### ISSUE TITLE
Duplicate (ctrl+d) w/o selection causes crash

### ISSUE THREAD

**Issue by Lailou12** [sevenc-nanashi/MikuMikuWorld4CC#35]
Update: it seems the crash was made by this string i found in my clipboard:
MikuMikuWorld clipboard
{damagesnull,hiSpeedChangesnull,holdsnull,notes[{criticaltrue,flicknone,frictiontrue,lane0.0,tick0,width6.0}]}
"[json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing object key - invalid literal; last read: "{d"; expecting string literal"
i really don't know how this got into my clipboard without quotes, can someone tell me what is going on

**Comment by mikreo** [comment]
Should be fixed in next version. The behaviour of duplicate is changed to always add to clipboard, instead of trying (and failing) to preserve it.
