### ISSUE TITLE
Flagged as  a trojan.

### ISSUE THREAD

**Issue by auxxyu** [sevenc-nanashi/MikuMikuWorld4CC#58]
the normal one isnt flagged but this is?

**Comment by auxxyu** [comment]
![Screenshot 2024-09-13 054404](https://github.com/user-attachments/assets/8336496e-7453-4cab-bbb1-5232c37a2a38)

**Comment by sevenc-nanashi** [comment]
There is nothing I can do; these anti-viruses are closed source, so I can't know what is causing mmw to get flagged.

If you're worry about the trojan warning, there is a perfect solution:
- Learn about C++
- Read the entire codebase, and check if there is something malicious
- Compile program by yourself

**Comment by auxxyu** [comment]
K
